### PR TITLE
Remove opengl in GitHub ci

### PR DESCRIPTION
**Pull request by jo-mueller**
Fixes #27

### CODE REVIEW

**Comment by jo-mueller** [comment]
I changed this PR to a draft PR - working in a PR is still necessary, otherwise it's not possible to examine whether the github CI runs smoothly or not.

**Comment by haesleinhuepf** [comment]
Also please check the merge target branch. It looks like not all commits are related to OpenGL

**Comment by jo-mueller** [comment]
Ah yes, this branch is based on [this branch](https://github.com/BiAPoL/napari-crop/tree/unique_layer_names) rather than main. 

I will not merge this unless #24 is merged.

**Comment by zoccoler** [comment]
Hi @jo-mueller ,

Maybe we could revisit this one now. The aforementioned branches were merged into main.

**Pull request closed without merging**
